apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-c
  template:
    metadata:
      labels:
        app: service-c
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: service-c
        image: prarthanabahuguna/service-c-stats:latest
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: service-c-config
