apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-c-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: service-c
  endpoints:
  - port: metrics
    interval: 30s
