apiVersion: v1
kind: Service
metadata:
  name: service-c
  labels:
    app: service-c
spec:
  type: ClusterIP
  selector:
    app: service-c
  ports:
    - name: metrics
      port: 4000
      targetPort: 4000
